Repository jenkinsci/copyartifact-plugin, pull requests merged in 2023-08, with the labels that each got.

#198 Run parallel tests in CI
  Jenkinsfile
  pom.xml
Labels: developer

#199 Remove hard coded surefire config
  pom.xml
Labels: test

#204 Test with Java 21
  Jenkinsfile
Labels: chore
