Repository jenkinsci/copyartifact-plugin, pull requests merged in 2023-01, with the labels that each got.

#163 Removing test dep on `compress-artifacts`
  pom.xml
  src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
Labels: developer

#166 Increase spotbugs checks
  pom.xml
  src/spotbugs/excludesFilter.xml
Labels: test

#168 Use optional maven integration 3.16, not 3.19
  pom.xml
Labels: bugfix

#169 Add `includeBuildNumberInTargetPath` configuration parameter
  README.adoc
  src/main/java/hudson/plugins/copyartifact/CopyArtifact.java
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config.jelly
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_de.properties
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_ja.properties
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/help-includeBuildNumberInTargetPath.html
  src/main/webapp/help-flatten-optional.html
  src/test/java/hudson/plugins/copyartifact/CopyArtifactTest.java
  src/test/java/hudson/plugins/copyartifact/testutils/CopyArtifactUtil.java
Labels: enhancement

#171 Remove empty translation properties
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_de.properties
  src/main/resources/hudson/plugins/copyartifact/CopyArtifact/config_ja.properties
Labels: bug
